// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNrrk8N961QH6c3AiSWKKP1dgQIxJA1M',
    appId: '1:351954591846:web:60429c813bdda04a258da7',
    messagingSenderId: '351954591846',
    projectId: 'notitest-86568',
    authDomain: 'notitest-86568.firebaseapp.com',
    storageBucket: 'notitest-86568.appspot.com',
    measurementId: 'G-CKEPGC6WY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG5bZqox3Mm4Z_Hqlc2JnZ2oWeQS9sUS0',
    appId: '1:351954591846:android:7210fdb94518ea38258da7',
    messagingSenderId: '351954591846',
    projectId: 'notitest-86568',
    storageBucket: 'notitest-86568.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9m0zoR36GlJNltKYbHF6HJ_5KzySGkWM',
    appId: '1:351954591846:ios:1c1fe961d898623f258da7',
    messagingSenderId: '351954591846',
    projectId: 'notitest-86568',
    storageBucket: 'notitest-86568.appspot.com',
    iosClientId: '351954591846-atc20s2hsjib5hbc22jieejqvasrfld2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudMessagingFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9m0zoR36GlJNltKYbHF6HJ_5KzySGkWM',
    appId: '1:351954591846:ios:1c1fe961d898623f258da7',
    messagingSenderId: '351954591846',
    projectId: 'notitest-86568',
    storageBucket: 'notitest-86568.appspot.com',
    iosClientId: '351954591846-atc20s2hsjib5hbc22jieejqvasrfld2.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudMessagingFire',
  );
}
